# App container which provides the php environment
app:
  # For development of the image comment out the 'image' line and replace with the next line
  #build: .
  image: sebobo/shel.dockerflow:3.0.4
  hostname: dockerflow
  domainname: dev
  volumes_from:
    - data
  volumes:
    - ./Configuration/Web/ip_address.txt:/ip_address.txt:ro
    - ./Scripts/EntryPoint/app.sh:/entrypoint.sh:ro
  expose:
    - "9000"
  links:
    - db
    - mail
    - redis
    - elasticsearch

# Passive data container which only provides a shared filesystem for the other containers
data:
  image: mariadb:10.0
  command: echo "Data container has started"
  volumes:
    - ../../../..:/var/www
    - /var/lib/mysql

db:
  image: mariadb:10.0
  volumes_from:
    - data
  volumes:
    - ./Scripts/EntryPoint/db.sh:/entrypoint.sh:ro
  ports:
    - "3307:3306"
  entrypoint: /entrypoint.sh
  command: mysqld
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: dockerflow dockerflow_test

web:
  image: nginx:1.7
  ports:
    - "8080:8080"
  volumes:
    - ./Configuration/Web/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./Configuration/Web/nginx_vhost_merged.conf:/etc/nginx/conf.d/default.conf:ro
    - ./Configuration/Web/ip_address.txt:/ip_address.txt:rw
    - ./Scripts/EntryPoint/web.sh:/entrypoint.sh:ro
  volumes_from:
    - data
  links:
    - app

mail:
  image: mailhog/mailhog:latest
  ports:
    - "8025:8025"

redis:
  image: redis:3.0
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch:1.4
  ports:
    - "9200:9200"
  volumes:
    - ./Configuration/ElasticSearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
